### ISSUE TITLE
Add / Update Pet Not working

### ISSUE THREAD

**Issue by springframeworkguru** [springframeworkguru/sfg-pet-clinic#69]
Template errors in Thymeleaf

**Comment by gregbown** [comment]
There is no update method, only save and it appears that the owner is null and all the owner id's and pet id's are also null in the save method.  The owner is defined in the initCreationForm method however the reference is lost in processUpdateForm

**Comment by gregbown** [comment]
Adding or updating was throwing an error or just loading the owner with the same pet unchanged.
[This fix solved the adding new pet](https://github.com/cassiusvm/sfg-pet-clinic/commit/d452aadf8955d790884b0d9567838d0635271b1f) and [this fix resolved updating a pet](https://github.com/springframeworkguru/sfg-pet-clinic/issues/99#issuecomment-447121223)

**Comment by MehulBhati** [comment]
The error here is in PetType class ,i have fixed the toString() to handle Null pointer Exception of Thymeleaf,just make a small change,it will get fixed,no need to change any other thing of John's code.

import jakarta.persistence.*;
import lombok.*;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "types")
public class PetType extends BaseEntity {

    @Builder
    public PetType(Long id, String name) {
        super(id);
        this.name = name;
    }

    @Column(name =  "name")
    private String name;

    @Override
    public String toString() {
        return name != null ? name : "";

    }

}
